module.exports = {
  accounts: [
    {
      id: 1,
      name: "Northstar SaaS",
      industry: "B2B SaaS",
      monthlyBudget: 15000,
    },
  ],
  importRuns: [
    {
      id: 1,
      fileName: "northstar-saas-sample.csv",
      accountName: "Northstar SaaS",
      resourceCount: 10,
      totalSpend: 11798,
      projectedSavings: 4138,
      mode: "sample",
      createdAt: "2026-07-01T09:30:00.000Z",
    },
    {
      id: 2,
      fileName: "qa-export-june.csv",
      accountName: "QA Export",
      resourceCount: 6,
      totalSpend: 6240,
      projectedSavings: 1840,
      mode: "sample",
      createdAt: "2026-07-01T15:10:00.000Z",
    },
  ],
  resources: [
    {
      id: 1,
      accountId: 1,
      service: "EC2",
      resourceName: "api-worker-3",
      environment: "prod",
      region: "us-east-1",
      status: "active",
      utilizationPct: 12,
      monthlyCost: 2480,
      ownerTeam: "Platform",
      lastUsedDays: 8,
      recommendationType: "rightsize",
      recommendationTitle: "Rightsize the API worker fleet",
      recommendationDetail:
        "The workload is consistently under 15% utilization, so the instance family can be reduced without affecting peak traffic.",
      estimatedMonthlySavings: 930,
      priority: "high",
    },
    {
      id: 2,
      accountId: 1,
      service: "RDS",
      resourceName: "customer-db",
      environment: "prod",
      region: "us-east-1",
      status: "active",
      utilizationPct: 82,
      monthlyCost: 1750,
      ownerTeam: "Data",
      lastUsedDays: 0,
      recommendationType: "commitment",
      recommendationTitle: "Buy a reserved instance for the customer database",
      recommendationDetail:
        "Usage is stable and predictable, making this a strong candidate for a committed capacity discount.",
      estimatedMonthlySavings: 420,
      priority: "high",
    },
    {
      id: 3,
      accountId: 1,
      service: "RDS",
      resourceName: "staging-db",
      environment: "staging",
      region: "us-east-1",
      status: "idle",
      utilizationPct: 4,
      monthlyCost: 640,
      ownerTeam: "Data",
      lastUsedDays: 21,
      recommendationType: "schedule",
      recommendationTitle: "Schedule staging database shutdown windows",
      recommendationDetail:
        "The staging database is mostly idle outside working hours and can be powered down nightly and on weekends.",
      estimatedMonthlySavings: 380,
      priority: "high",
    },
    {
      id: 4,
      accountId: 1,
      service: "EBS",
      resourceName: "unattached-volume-12",
      environment: "dev",
      region: "us-west-2",
      status: "available",
      utilizationPct: 0,
      monthlyCost: 128,
      ownerTeam: "Platform",
      lastUsedDays: 31,
      recommendationType: "cleanup",
      recommendationTitle: "Delete unattached storage",
      recommendationDetail:
        "This volume is detached and has not been touched in over a month. Removing it stops avoidable block storage charges.",
      estimatedMonthlySavings: 128,
      priority: "medium",
    },
    {
      id: 5,
      accountId: 1,
      service: "NAT Gateway",
      resourceName: "shared-nat-1",
      environment: "prod",
      region: "us-east-1",
      status: "active",
      utilizationPct: 91,
      monthlyCost: 910,
      ownerTeam: "Platform",
      lastUsedDays: 0,
      recommendationType: "network-optimization",
      recommendationTitle: "Reduce NAT data transfer",
      recommendationDetail:
        "Route S3 and CloudWatch traffic through VPC endpoints to cut avoidable egress and NAT processing charges.",
      estimatedMonthlySavings: 240,
      priority: "medium",
    },
    {
      id: 6,
      accountId: 1,
      service: "ElastiCache",
      resourceName: "session-cache",
      environment: "prod",
      region: "us-east-1",
      status: "active",
      utilizationPct: 69,
      monthlyCost: 790,
      ownerTeam: "App",
      lastUsedDays: 1,
      recommendationType: "rightsize",
      recommendationTitle: "Reduce cache node size off-peak",
      recommendationDetail:
        "The cache is healthy but has headroom. A smaller node class plus a schedule can preserve latency while lowering spend.",
      estimatedMonthlySavings: 210,
      priority: "medium",
    },
    {
      id: 7,
      accountId: 1,
      service: "EC2",
      resourceName: "batch-node-1",
      environment: "staging",
      region: "us-west-2",
      status: "active",
      utilizationPct: 7,
      monthlyCost: 1180,
      ownerTeam: "Analytics",
      lastUsedDays: 12,
      recommendationType: "schedule",
      recommendationTitle: "Scale batch compute to zero after runs",
      recommendationDetail:
        "Batch traffic is sporadic and the node spends most of the day idle. Schedule start/stop windows around the pipeline.",
      estimatedMonthlySavings: 560,
      priority: "high",
    },
    {
      id: 8,
      accountId: 1,
      service: "Snapshots",
      resourceName: "monthly-backup-set",
      environment: "prod",
      region: "us-east-1",
      status: "active",
      utilizationPct: 0,
      monthlyCost: 260,
      ownerTeam: "Platform",
      lastUsedDays: 45,
      recommendationType: "cleanup",
      recommendationTitle: "Archive or delete stale snapshots",
      recommendationDetail:
        "The backup set is older than retention policy and can be compacted into cheaper archival storage or removed.",
      estimatedMonthlySavings: 140,
      priority: "low",
    },
    {
      id: 9,
      accountId: 1,
      service: "OpenSearch",
      resourceName: "search-prod",
      environment: "prod",
      region: "us-east-1",
      status: "active",
      utilizationPct: 74,
      monthlyCost: 2240,
      ownerTeam: "Search",
      lastUsedDays: 0,
      recommendationType: "commitment",
      recommendationTitle: "Commit steady search capacity",
      recommendationDetail:
        "Search traffic is steady enough to benefit from reserved capacity pricing for the core cluster.",
      estimatedMonthlySavings: 520,
      priority: "high",
    },
    {
      id: 10,
      accountId: 1,
      service: "EKS",
      resourceName: "qa-node-group",
      environment: "qa",
      region: "us-west-2",
      status: "active",
      utilizationPct: 14,
      monthlyCost: 1420,
      ownerTeam: "QA",
      lastUsedDays: 10,
      recommendationType: "rightsize",
      recommendationTitle: "Reduce the QA node group footprint",
      recommendationDetail:
        "The QA cluster is oversized for its current test load and can shrink without affecting deployments.",
      estimatedMonthlySavings: 610,
      priority: "high",
    },
  ],
};
